---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
components:
  - ../../components/alerts
resources:
  - ./cert-manager/ks.yaml
  - ./namespace.yaml
