---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodsweep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: woodsweep-secret
    template:
      data:
        KOPIA_PASSWORD: "{{ .REPOSITORY_PASSWORD }}"
        KOPIA_SERVER_CONTROL_PASSWORD: "{{ .BOOTSTRAP_PASSWORD }}"
        KOPIA_SERVER_PASSWORD: "{{ .WOODMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: woodsweep
