---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: bind-primary
    files:
      - ./named.conf
      - ./db.10.in-addr.arpa
      - ./db.woodleigh.vic.edu.au
      - ./db.woodleighschool.net
generatorOptions:
  disableNameSuffixHash: true
