---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: selectronic-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: selectronic-exporter
  interval: 1h
  values:
    controllers:
      selectronic-exporter:
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/selectronic-exporter
              tag: 0.1.2@sha256:982bef13b7892f8b85e32e410918a1d7b3d456081b468edd5cc9f2b4202b1bbc
            env:
              TZ: Australia/Melbourne
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        ports:
          http:
            port: 9788
