---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: selectronic-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: selectronic-exporter
  interval: 1h
  values:
    controllers:
      selectronic-exporter:
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/selectronic-exporter
              tag: 0.1.3@sha256:1f975beed25748ae75e99b1159e4e5bd5bf0d9cc7e7576201156406c356cd04a
            env:
              TZ: Australia/Melbourne
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        ports:
          http:
            port: 9788
