---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: msteams
    repeatInterval: 12h
    routes:
      - receiver: blackhole
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
      - receiver: msteams
        matchers:
          - name: severity
            value: critical
            matchType: =
    groupBy:
      - alertname
      - cluster
      - job
    groupInterval: 5m
    groupWait: 1m

  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =

  receivers:
    - name: blackhole
    - name: msteams
      msteamsv2Configs:
        - webhookURL:
            name: alertmanager-secret
            key: ALERTMANAGER_TEAMS_WEBHOOK
          text: |-
            {{- range .Alerts }}

            **Alert:** {{ .Labels.alertname }}

            {{- if ne .Annotations.description "" }}

            {{ .Annotations.description }}
            {{- else if ne .Annotations.summary "" }}

            {{ .Annotations.summary }}
            {{- else if ne .Annotations.message "" }}

            {{ .Annotations.message }}
            {{- else }}

            Alert description not available
            {{- end }}

            **Status:** `{{ .Status }}`

            **Starts:** {{ .StartsAt }}
            {{- if .EndsAt }}

            **Ends:** {{ .EndsAt }}
            {{- end }}

            **Source:** [Open in Alertmanager](https://alertmanager.woodleighschool.net)

            {{- if gt (len .Labels.SortedPairs) 0 }}

            **Labels:**
            {{- range .Labels.SortedPairs }}
            - **{{ .Name }}:** `{{ .Value }}`
            {{- end }}
            {{- end }}

            ---
            {{- end }}
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
