---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy:
      - alertname
      - job
    groupInterval: 10m
    groupWait: 1m
    receiver: msteams
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
      - receiver: msteams
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: "null"
    - name: msteams
      msteamsv2Configs:
        - webhookURL:
            name: alertmanager-secret
            key: ALERTMANAGER_TEAMS_WEBHOOK
          text: |-
            {{- $ctx := dict "sep" "" -}}
            {{- range .Alerts }}
            {{ $ctx.sep }}
            **{{ .Annotations.summary | default .Labels.alertname }}**

            {{- if .Annotations.description }}
            {{ .Annotations.description }}
            {{- end }}

            **Status:** `{{ .Status }}`
            **Starts:** {{ .StartsAt }}{{ if .EndsAt }}
            **Ends:** {{ .EndsAt }}{{ end }}
            **Source:** [Open in source]({{ .GeneratorURL }})

            **Labels**
            {{- range .Labels.SortedPairs }}
            - **{{ .Name }}**: `{{ .Value }}`
            {{- end }}

            {{- $_ := set $ctx "sep" "\n---\n" -}}
            {{- end }}
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
