---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onomazo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onomazo-secret
    template:
      data:
        JAMF_CLIENT_ID: "{{ .JAMF_CLIENT_ID }}"
        JAMF_CLIENT_SECRET: "{{ .JAMF_CLIENT_SECRET }}"
        JAMF_URL: "{{ .JAMF_URL }}"
        MICROSOFT_CLIENT_ID: "{{ .ENTRA_CLIENT_ID }}"
        MICROSOFT_CLIENT_SECRET: "{{ .ENTRA_CLIENT_SECRET }}"
        MICROSOFT_TENANT_ID: "{{ .ENTRA_TENANT_ID }}"
  dataFrom:
    - extract:
        key: onomazo
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onomazo-overlay
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onomazo-overlay
    template:
      data:
        overlay.yaml: "{{ .CONFIG_OVERLAY }}"
  dataFrom:
    - extract:
        key: onomazo
