---
# yaml-language-server: $schema=https://schemas.hydaz.com/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: client-traffic
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: internal
  clientIPDetection:
    xForwardedFor:
      numTrustedHops: 1
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
---
# yaml-language-server: $schema=https://schemas.hydaz.com/gateway.envoyproxy.io/clienttrafficpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: client-traffic-cloudflare
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: cloudflare
  clientIPDetection:
    customHeader:
      name: "CF-Connecting-IP"
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
