---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app setrecoverypassword
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: setrecoverypassword
  values:
    controllers:
      setrecvoerypassword:
        type: cronjob
        cronjob:
          schedule: "@daily"
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          timeZone: "Australia/Melbourne"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/setrecoverypassword
              tag: 2.0.1@sha256:e70f0ce05fac42ef0bd66e49a2bb0c30cfb19536b1c69d65aafaf88415604f07
            env:
              PASSWORD_LENGTH: 10
              LOG_LEVEL: debug
              INSTANCE_DOMAIN: wdm.jamfcloud.com
              TZ: Australia/Melbourne
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
