---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app setrecoverypassword
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: setrecoverypassword
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      setrecvoerypassword:
        type: cronjob
        cronjob:
          schedule: "@daily"
          suspend: true
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          timeZone: "Australia/Melbourne"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/setrecoverypassword
              tag: 1.2.1@sha256:03fc54aac1053cd367af33eb65512fee0964e4b888dd1f175fb079b8e7ac15df
            env:
              JAMF_HOST: wdm.jamfcloud.com
              LOG_LEVEL: debug
              UPDATE_NOW: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: *app
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
