---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: setrecoverypassword
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: ceph-block
