---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  interval: 1h
  values:
    crds:
      create: true
    monitoring:
      podMonitorEnabled: false
      grafanaDashboard:
        create: true
