---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: updateuserinfo
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: updateuserinfo
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      updateuserinfo:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/updateuserinfo
              tag: latest@sha256:f41f83636fa601f6be54ff432c79bb198146eafdb53070bfc8605ce2c733802a
            env:
              JAMF_HOST: wdm.jamfcloud.com
              LDAP_HOST: wdc01.woodleighschool.net
              UPDATE_NOW: true
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
