---
# yaml-language-server: $schema=https://schemas.hydaz.com/k8s.mariadb.com/mariadb_v1alpha1.json
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  # renovate: datasource=docker depName=docker.io/library/mariadb
  image: docker.io/library/mariadb:11.8.8@sha256:7974b628cbb4a37c4108d82f1e1d1123d1857ae3d94ab6fb20b8ad8580c271c8
  replicas: 3
  replication:
    enabled: true
    replica:
      replPasswordSecretKeyRef:
        name: mariadb-secret
        key: REPLICATION_PASSWORD
      bootstrapFrom:
        physicalBackupTemplateRef:
          name: mariadb-backup
      recovery:
        enabled: true
  storage:
    size: 64Gi
    storageClassName: openebs-hostpath
  affinity:
    antiAffinityEnabled: true
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
    limits:
      memory: 2Gi
  service:
    metadata:
      annotations:
        gatus.home-operations.com/endpoint: |-
          group: services
          interval: 15s
          conditions:
            - "[CONNECTED] == true"
  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: root-password
  myCnf: |-
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1600MB
    max_allowed_packet=1GB
    log_warnings=0
  bootstrapFrom:
    s3:
      accessKeyIdSecretKeyRef:
        name: mariadb-secret
        key: N3_ACCESS_KEY_ID
      bucket: sc-ops
      endpoint: n3.woodleighschool.net
      prefix: mariadb
      secretAccessKeySecretKeyRef:
        name: mariadb-secret
        key: N3_SECRET_ACCESS_KEY
      tls:
        enabled: true
    backupContentType: Physical
    stagingStorage:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 64Gi
        accessModes:
          - ReadWriteMany
        storageClassName: ceph-filesystem
  metrics:
    enabled: true
  updateStrategy:
    autoUpdateDataPlane: true
