---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app signin-ui
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: signin-ui
  values:
    controllers:
      signin-ui:
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/papercut-checkin
              tag: 0.3.0@sha256:14c6635092339f6188d955a33228f47e5c47f1dfd88c661f2bd498c5a45ac1a4
            env:
              TZ: Australia/Melbourne
              SIGNIN_AREAS: |-
                Wellbeing
                Learning Enhancement
              NAMES_LIST: |-
                John Smith
                Jane Doe
                Alex Johnson
                Sarah Wilson
                Michael Brown
                Emma Davis
                James Miller
                Olivia Garcia
                William Martinez
                Sophia Anderson
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    persistence:
      config:
        existingClaim: *app
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /app/instance
            subPath: instance
