---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodstar-mdp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: woodstar-mdp-secret
    template:
      data:
        WOODSTAR_MDP_KEY: "{{ .MDP_KEY }}"
  dataFrom:
    - extract:
        key: woodstar
