---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bind-primary
spec:
  components:
    - ../../../../../components/kopiur/backup
  interval: 1h
  path: ./kubernetes/apps/base/network/bind/primary
  postBuild:
    substitute:
      APP: bind-primary
      KOPIUR_CAPACITY: 1Gi
      KOPIUR_PGID: "53"
      KOPIUR_PUID: "53"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bind
spec:
  interval: 1h
  path: ./kubernetes/apps/base/network/bind/resolver
  postBuild:
    substitute:
      DNS_ADDRESS: 10.10.69.53
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
