---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kea
spec:
  components:
    - ../../../../../components/kopiur/backup
    - ../../../../sc/network/kea
  interval: 1h
  path: ./kubernetes/apps/base/network/kea/app
  postBuild:
    substitute:
      APP: kea
      KEA_ADDRESS: 10.10.69.67
      KOPIUR_CAPACITY: 1Gi
      KOPIUR_PGID: "101"
      KOPIUR_PUID: "100"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: network
