---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network
components:
  - ../../../components/alerts
  - ../../../components/kopiur/secret
resources:
  - ./bind.yaml
  - ./bind-dns.yaml
  - ./certificates.yaml
  - ./cloudflare-dns.yaml
  - ./cloudflare-tunnel.yaml
  - ./envoy-gateway.yaml
  - ./kea.yaml
  - ./namespace.yaml
  - ./windows-dns.yaml
