---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jcdssync
spec:
  chartRef:
    kind: OCIRepository
    name: jcdssync
  interval: 1h
  values:
    controllers:
      nginx:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/library/nginx
              tag: 1.29.3-alpine@sha256:b3c656d55d7ad751196f21b7fd2e8d4da9cb430e32f646adcf92441b72f82b14
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 80
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi
      jcdssync:
        type: cronjob
        cronjob:
          schedule: "0 */6 * * *"
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          timeZone: "Australia/Melbourne"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/jcdssync
              tag: 3.0.0@sha256:f77fa990e66d6a8a845b7d6c83f6783a02e5b672ae855c8142600a854cbf5f1a
            env:
              TZ: Australia/Melbourne
              INSTANCE_DOMAIN: https://wdm.jamfcloud.com
            args:
              - --log-level=debug
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/instance
                        operator: In
                        values:
                          - jcdssync
                      - key: app.kubernetes.io/controller
                        operator: In
                        values:
                          - nginx
                  topologyKey: kubernetes.io/hostname
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      nginx:
        controller: nginx
        ports:
          http:
            port: *port
    route:
      nginx:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      packages:
        existingClaim: "{{ .Release.Name }}-cache"
        globalMounts:
          - path: /packages
      nginx-config:
        type: configMap
        name: jcdssync-configmap
        advancedMounts:
          nginx:
            app:
              - path: /etc/nginx/conf.d/default.conf
                subPath: default.conf
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /var/cache/nginx
            subPath: cache-nginx
          - path: /var/run
            subPath: run
