---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jamf-user-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jamf-user-sync-secret
    template:
      data:
        JAMF_CLIENT_ID: "{{ .JAMF_CLIENT_ID }}"
        JAMF_CLIENT_SECRET: "{{ .JAMF_CLIENT_SECRET }}"
        LDAP_USERNAME: "{{ .LDAP_USERNAME }}"
        LDAP_CREDENTIALS: "{{ .LDAP_CREDENTIALS }}"
  dataFrom:
    - extract:
        key: updateuserinfo
