---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app alloy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: alloy
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    alloy:
      configMap:
        create: false
        name: &configMap alloy-configmap
        key: config.alloy
    controller:
      podAnnotations:
        configmap.reloader.stakater.com/reload: *configMap
    serviceMonitor:
      enabled: true
