---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: _
metadata:
  name: _
spec:
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        status.phase != 'Running'
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: |-
        !(status.phase in ['Resolving', 'Restoring'])
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      expr: |-
        status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: k8s.mariadb.com/v1alpha1
      kind: MariaDB
      expr: |-
        status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
