---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-object-storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prometheus-object-storage-secret
    template:
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: sc-ops
            endpoint: n3.woodleighschool.net
            access_key: "{{ .N3_ACCESS_KEY_ID }}"
            secret_key: "{{ .N3_SECRET_ACCESS_KEY }}"
            insecure: false
  dataFrom:
    - extract:
        key: n3
