---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/alerts
resources:
  - ./freshservice-label/ks.yaml
  - ./home-assistant/ks.yaml
  - ./leave-calendar/ks.yaml
  - ./metabasis/ks.yaml
  - ./namespace.yaml
  - ./onomazo/ks.yaml
  - ./signin-ui/ks.yaml
  - ./snipe-it/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./woodgate/ks.yaml
  - ./woodsweep/ks.yaml
  - ./woodstar/ks.yaml
