---
endpoints:
  - name: "${APP}"
    group: "${GATUS_GROUP:=external}"
    url: "https://${GATUS_SUBDOMAIN:=${APP}}.${GATUS_DOMAIN:=woodleighschool.net}${GATUS_PATH:=/}"
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == ${GATUS_STATUS:=200}"
