---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagekey_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: woodsweep
spec:
  clusterRef:
    name: garage
  bucketPermissions:
    - bucketRef:
        name: woodsweep
      read: true
      write: true
  secretTemplate:
    name: woodsweep-s3-credentials
