---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodgate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: woodgate
  values:
    controllers:
      woodgate:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/woodgate
              tag: 1.0.1@sha256:d0c5eb25e1bb9430576c14bd4851aed6d27b03771d81c62a9f12b7f5c415796c
            env:
              ENTRA_SYNC_ENABLED: true
              ENTRA_SYNC_INTERVAL: 24h
              TZ: Australia/Melbourne
              WOODGATE_BASE_URL: https://{{ .Release.Name }}.woodleighschool.net
              WOODGATE_MEDIA_ROOT: /media
              WOODGATE_PORT: &port 8080
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      media:
        existingClaim: "{{ .Release.Name }}-media"
      tmp:
        type: emptyDir
