---
web:
  port: ${GATUS_WEB_PORT}

storage:
  type: sqlite
  path: /data/sqlite.db
  caching: true

metrics: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/112675474
  link: https://github.com/woodleighschool
  buttons:
    - name: Github
      link: https://github.com/woodleighschool
    - name: Homelab
      link: https://github.com/woodleighschool/sc-ops

connectivity:
  checker:
    target: 10.1.110.29:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.woodleighschool.net
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    client:
      dns-resolver: tcp://10.1.110.29:53
    conditions:
      - "[STATUS] == 404"
