---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/112675474
  link: https://github.com/woodleighschool
  buttons:
    - name: Github
      link: https://github.com/woodleighschool
    - name: Homelab
      link: https://github.com/woodleighschool/sc-ops

web:
  port: ${GATUS_WEB_PORT}
