---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
# Until Flux follows the new sync path; removed in the next commit.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../clusters/sc
