---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/alerts
resources:
  - ./blackbox-exporter/ks.yaml
  - ./fluent-bit/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./json-exporter/ks.yaml
  - ./keda/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./namespace.yaml
  - ./silence-operator/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./snmp-exporter/ks.yaml
  - ./victoria-logs/ks.yaml
