---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bind-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bind-dns-secret
    template:
      data:
        EXTERNAL_DNS_RFC2136_TSIG_SECRET: '{{ index . "tsig-external-dns-${CLUSTER}" }}'
  dataFrom:
    - extract:
        key: bind
