---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-cluster
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-cluster
  interval: 1h
  values:
    fullnameOverride: victoria-metrics-cluster
    victoria-metrics-operator:
      enabled: false
    defaultDashboards:
      enabled: false
    defaultDatasources:
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true
          instanceSelector:
            matchLabels:
              dashboards: monitoring
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
    vmauth:
      enabled: false
    grafana:
      enabled: false
      forceDeployDatasource: true
    prometheus-node-exporter:
      enabled: false
    kube-state-metrics:
      enabled: false
    kubelet:
      enabled: false
    kubeApiServer:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    coreDns:
      enabled: false
    kubeDns:
      enabled: false
    kubeProxy:
      enabled: false
    vmsingle:
      enabled: true
      spec:
        retentionPeriod: 90d
        replicaCount: 1
        extraArgs:
          promscrape.dropOriginalLabels: "true"
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: ceph-block
    vmagent:
      enabled: true
      rbac:
        namespaced: true
      spec:
        selectAllByDefault: false
        scrapeInterval: 30s
        scrapeConfigNamespaceSelector:
          matchLabels:
            monitoring.woodleighschool.net/enabled: "true"
        scrapeConfigSelector:
          matchLabels:
            monitoring.woodleighschool.net/scrape: "true"
        extraArgs:
          promscrape.dropOriginalLabels: "true"
          promscrape.streamParse: "true"
