---
# yaml-language-server: $schema=https://raw.githubusercontent.com/rajsinghtech/garage-operator/refs/heads/main/schemas/garagekey_v1beta1.json
apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: woodstar-munki
spec:
  clusterRef:
    name: garage
  bucketPermissions:
    - bucketRef:
        name: woodstar-munki
      read: true
      write: true
  secretTemplate:
    name: woodstar-munki-s3-credentials
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default"
    accessKeyIdKey: WOODSTAR_MUNKI_S3_ACCESS_KEY
    secretAccessKeyKey: WOODSTAR_MUNKI_S3_SECRET_KEY
    endpointKey: WOODSTAR_MUNKI_S3_ENDPOINT
    regionKey: WOODSTAR_MUNKI_S3_REGION
    additionalData:
      WOODSTAR_MUNKI_S3_BUCKET: woodstar-munki
      WOODSTAR_MUNKI_S3_PUBLIC_ENDPOINT: https://garage.woodleighschool.net
      WOODSTAR_MUNKI_S3_PATH_STYLE: "true"
      WOODSTAR_MUNKI_S3_PRESIGN_TTL: 15m
