---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  values:
    fullnameOverride: *app
    extraArgs:
      - --config.expand-environment-variables
      - --config.file=/etc/snmp_exporter/snmp.yml
      - --log.level=debug
    envFrom:
      - secretRef:
          name: snmp-secret
    extraConfigmapMounts:
      - name: snmp-exporter-configmap
        mountPath: /etc/snmp_exporter/snmp.yml
        subPath: snmp.yml
        configMap: snmp-exporter-configmap
        readOnly: true
    serviceMonitor:
      enabled: true
      params:
        #- name: itups1
        #  module:
        #    - apcups
        #  target: 172.20.1.15
        #  auth:
        #    - snmp_v3
        #- name: itups2
        #  module:
        #    - apcups
        #  target: 172.20.1.16
        #  auth:
        #    - snmp_v3
        - name: adminups
          module:
            - eatonups
          target: 10.10.28.210
          auth:
            - snmp_v3
      path: /snmp
      scrapeTimeout: 30s
      relabelings:
        - sourceLabels:
            - __param_target
          targetLabel: instance
