---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grinch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grinch-secret
    template:
      data:
        DATABASE_HOST: postgres-rw.databases.svc.cluster.local
        DATABASE_NAME: grinch
        DATABASE_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        DATABASE_USER: "{{ .DATABASE_USER }}"
        ENTRA_CLIENT_ID: "{{ .ENTRA_CLIENT_ID }}"
        ENTRA_CLIENT_SECRET: "{{ .ENTRA_CLIENT_SECRET }}"
        ENTRA_TENANT_ID: "{{ .ENTRA_TENANT_ID }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        LOCAL_ADMIN_PASSWORD: "{{ .LOCAL_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: grinch
