---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grinch
spec:
  chartRef:
    kind: OCIRepository
    name: grinch
  interval: 1h
  values:
    controllers:
      grinch:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/grinch
              tag: 0.0.2@sha256:000342f1ada0c40253cb0295bb7af748e647e02c879c9fbead4f64e92d2b3f65
            env:
              ENTRA_SYNC_ENABLED: true
              ENTRA_SYNC_INTERVAL: 24h
              GRINCH_BASE_URL: https://{{ .Release.Name }}.woodleighschool.net
              GRINCH_PORT: &port 8080
              LOG_LEVEL: debug
              TZ: Australia/Melbourne
              EVENT_RETENTION_DAYS: 14
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
      sync:
        hostnames:
          - "{{ .Release.Name }}.woodleigh.vic.edu.au"
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
            matches:
              - path:
                  type: PathPrefix
                  value: /sync
    persistence:
      tmp:
        type: emptyDir
