---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodstar
spec:
  chartRef:
    kind: OCIRepository
    name: woodstar
  interval: 1h
  values:
    controllers:
      woodstar:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/woodstar
              tag: 0.0.4@sha256:bba1e8ae1e302e0aa64a1c19d97e990dd5d2ab57ed68e0a502c0f765304db15e
            env:
              TZ: Australia/Melbourne
              WOODSTAR_HOST: 0.0.0.0
              WOODSTAR_LOG_LEVEL: debug
              WOODSTAR_PORT: &port 8080
              WOODSTAR_PUBLIC_URL: https://{{ .Release.Name }}.woodleighschool.net
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      tmp:
        type: emptyDir
