---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:16.9@sha256:7f3990485b139ccf9e2222c8f106d97ac0331f313cb5278e7018ef38686bb561
  instances: 3
  storage:
    size: 8Gi
    storageClass: openebs-hostpath
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 2Gi
  managed:
    services:
      additional:
        # create a stub service for gatus to monitor
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: postgres
              annotations:
                gatus.home-operations.com/endpoint: |-
                  group: services
                  interval: 15s
                  conditions:
                    - "[CONNECTED] == true"
  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
  monitoring:
    enablePodMonitor: true
  primaryUpdateStrategy: unsupervised
