# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: leave-calendar-ghcr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: leave-calendar-ghcr-pull-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GHCR_USERNAME }}",
                "password": "{{ .GHCR_TOKEN }}",
                "auth": "{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: ghcr
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: leave-calendar
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: leave-calendar-secret
    template:
      data:
        APP_BASE_URL: "{{ .APP_BASE_URL }}"
        DATABASE_URL: "{{ .DATABASE_URL }}"
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        TEAM_CODE_SECRET: "{{ .TEAM_CODE_SECRET }}"
        MICROSOFT_CLIENT_ID: "{{ .MICROSOFT_CLIENT_ID }}"
        MICROSOFT_CLIENT_SECRET: "{{ .MICROSOFT_CLIENT_SECRET }}"
        MICROSOFT_TENANT_ID: "{{ .MICROSOFT_TENANT_ID }}"
  dataFrom:
    - extract:
        key: leave-calendar
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: leave-calendar-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: leave-calendar-config
    template:
      data:
        organisation.json: "{{ .ORG_CONFIG }}"
  dataFrom:
    - extract:
        key: leave-calendar
