---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: leave-calendar
spec:
  chartRef:
    kind: OCIRepository
    name: leave-calendar
  interval: 1h
  values:
    controllers:
      leave-calendar:
        containers:
          app:
            image:
              repository: ghcr.io/woodleighschool/leave-calendar
              tag: 2.1.2@sha256:45e610daa4987cb4f5ca1e764ce79177c09d2423a4e1aa35a1b9e51b3ee07e18
            env:
              TZ: Australia/Melbourne
              CALENDAR_SYNC_MAX_AGE_HOURS: 24
              VICTORIA_CALENDAR_URL: "https://www.vic.gov.au/sites/default/files/2026-06/Victorian-public-holiday-dates.ics"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 128Mi
    defaultPodOptions:
      imagePullSecrets:
        - name: leave-calendar-ghcr-pull-secret
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config-file:
        type: secret
        name: leave-calendar-config
        globalMounts:
          - path: /data/calendar/organisation.json
            subPath: organisation.json
