---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: munkireport
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: munkireport-secret
    template:
      data:
        #CLIENT_PASSPHRASES: "{{ .CLIENT_PASSPHRASES }}"
        CONNECTION_DATABASE: munkireport
        CONNECTION_DRIVER: mysql
        CONNECTION_HOST: mariadb-primary.databases.svc.cluster.local
        CONNECTION_PASSWORD: "{{ .CONNECTION_PASSWORD }}"
        CONNECTION_USERNAME: "{{ .CONNECTION_USERNAME }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: munkireport
