---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: munkireport
spec:
  chartRef:
    kind: OCIRepository
    name: munkireport
  interval: 1h
  values:
    controllers:
      munkireport:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/hydazz/munkireport
              tag: 5.8.0@sha256:c72aad67bdb87c626d710c642c48e37401c3b5af54ba6d4bbf03dde5955f4047
            env:
              AUTH_METHODS: NOAUTH
              ENABLE_BUSINESS_UNITS: "TRUE"
              MODULES: >-
                applications,
                appusage,
                ard,
                bluetooth,
                disk_report,
                extensions,
                filevault_status,
                findmymac,
                firewall,
                homebrew,
                homebrew_info,
                icloud,
                inventory,
                launchdaemons,
                location,
                machine,
                managedinstalls,
                mdm_status,
                ms_defender,
                ms_office,
                munkireport,
                munkireportinfo,
                network,
                power,
                printer,
                profile,
                security,
                sophos,
                users,
                wifi
              MODULE_SEARCH_PATHS: /var/www/html/vendor/tuxudo/
              SITENAME: MunkiReport
              TZ: Australia/Melbourne
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            #probes:
            #  liveness: &probes
            #    enabled: true
            #    custom: true
            #    spec:
            #      httpGet:
            #        path: /auth/login
            #        port: &port 80
            #      initialDelaySeconds: 0
            #      periodSeconds: 10
            #      timeoutSeconds: 1
            #      failureThreshold: 3
            #  readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: 80
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.woodleighschool.net"
        parentRefs:
          - name: envoy-internal
            namespace: network
    configMaps:
      config:
        data:
          composer.local.json: |-
            {
                "require": {
                    "tuxudo/icloud": "^3.7",
                    "tuxudo/browser_extensions": "^3.0",
                    "tuxudo/ms_defender": "^3.0",
                    "tuxudo/ms_office": "^3.7",
                    "tuxudo/launchdaemons": "^3.3"
                }
            }
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/www/html/vendor
            subPath: vendor
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /var/www/html/composer.local.json
            subPath: composer.local.json
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /var/www/html
            subPath: html
          - path: /var/run
            subPath: run
          - path: /tmp
            subPath: tmp
