---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: metabasis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: metabasis-secret
    template:
      data:
        METABASIS_DATABASE_URL: "postgres://{{ .DATABASE_USER }}:{{ .DATABASE_PASSWORD }}@postgres-rw.databases.svc.cluster.local:5432/metabasis?sslmode=disable"
        FRESHSERVICE_WEBHOOK_TOKEN: "{{ .FRESHSERVICE_WEBHOOK_TOKEN }}"
        MICROSOFT_CLIENT_ID: "{{ .ENTRA_CLIENT_ID }}"
        MICROSOFT_CLIENT_SECRET: "{{ .ENTRA_CLIENT_SECRET }}"
        MICROSOFT_TENANT_ID: "{{ .ENTRA_TENANT_ID }}"
  dataFrom:
    - extract:
        key: metabasis
